version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  phoenix:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    depends_on:
      - db